import React, { useRef, useEffect } from "react";
import CommonResourceComponent from "../commonResourceComponent";
import CommonResourceLeftSide from "../CommonResourceLeftSide";
import ReactangleTopImage from "../Resources14/Rectangle.svg"
import { Row, Col, Carousel } from "antd";
import "../Resources1/SingleResources.css"
import { Module1, Module4 } from "../AllResourcesData"
function SingleResource14() {


    const liList = [
        {
            list: "Return Components"
        },
        {
            list: "Risk Components"
        },
        {
            list: "Risk-Return Tradeoff"
        },
        {
            list: "Monitoring and Adjustments"
        },
        {
            list: "Conclusion"
        }
    ]
    const ReturnComponents = [
        {
            topTitle: "Rental Income",
            cardDetails: [
                {
                    cardBoldText: "Potential Return",
                    cardDescription: "Investors on Vaar receive a share of the rental income generated by the properties they own. This forms a consistent and predictable stream of passive income."

                },
                {
                    cardBoldText: "Analysis",
                    cardDescription: "The stability and regularity of rental income contribute to the overall return profile. Investors can evaluate the historical performance of similar properties and assess the potential for steady income."
                }
            ]
        }
    ]

    const RiskComponents =[
        {
            topTitle:"Market Risk",
            cardDetails:[
                {
                    cardBoldText:"Potential Risk",
                    cardDescription:"Real estate markets can be influenced by economic conditions, interest rates, and other macroeconomic factors."
                },
                {
                    cardBoldText:"Analysis",
                    cardDescription:"Understanding the broader economic environment and assessing how it might impact real estate markets is crucial. Historical market trends and potential future scenarios should be considered."
                }
            ]
        }
    ]
    const onChange = (currentSlide) => {
        // console.log(currentSlide);
    };
    const carouselRef = useRef(null);

    const handlePrev = () => {
        carouselRef.current.prev();
    };

    const handleNext = () => {
        carouselRef.current.next();
    };
    useEffect(() => {
        window.scrollTo(0, 0); // Scroll to the top when the component mounts or updates
      }, []);
    return (
        <>
            <CommonResourceComponent Resources="Resources" Module="Module 4" Chapter="Concept 4" Date="February 17, 2023" ResourceHeading="Risk-Return Analysis & Vaar" AuthorInfo="Stephanie Gordon, Content Manager, Vaar" topResourceImg={Module4[3].img} />
            <section>
                <div className="container p-0">
                    <Row>
                        <Col lg={6} md={6} className="hide-on-mobile">
                            <CommonResourceLeftSide MainLeftcontainerHeading="In this chapter" liList={liList} boxTitle="Try the product out for free." />
                        </Col>
                        <Col lg={18} md={18} className="full-width-on-mobile">
                            <div className="resources-right-container">
                                <p>Risk-return analysis is a fundamental principle in investment, assessing the relationship between the potential for higher returns and the associated level of risk. In the context of Vaar, a platform facilitating fractional ownership of real estate, the risk-return profile can be analyzed considering various factors. Here's a breakdown of how the risk-return analysis may be approached using Vaar:</p>
                                <div className="padding-slite"></div>
                                <h4>Return Components</h4>
                                <div className="pc-view-14">
                                    {ReturnComponents.map((item, index) => (
                                        <div key={index} className="RealEstate-Box">
                                            <h6>{index + 1}.&nbsp;{item.topTitle}</h6>
                                            <hr style={{ opacity: "1" }} />
                                            {item.cardDetails.map((card, cardIndex) => (
                                                <ul key={cardIndex}>
                                                    <li><b>{card.cardBoldText}</b>: {card.cardDescription}</li>
                                                </ul>
                                            ))}
                                        </div>
                                    ))}
                                </div>
                                <div className="mobile-view-14">
                                    <Carousel afterChange={onChange} ref={carouselRef} dots={true} autoplay >
                                        {ReturnComponents.map((item, index) => (
                                            <div key={index} className="RealEstate-Box">
                                                <h6>{index + 1}.&nbsp;{item.topTitle}</h6>
                                                <hr style={{ opacity: "1" }} />
                                                {item.cardDetails.map((card, cardIndex) => (
                                                    <ul key={cardIndex}>
                                                        <li><b>{card.cardBoldText}</b>: {card.cardDescription}</li>
                                                    </ul>
                                                ))}
                                            </div>
                                        ))}
                                    </Carousel>
                                </div>
                                <div className="padding-slite"></div>
                                <h4>Risk Components</h4>
                                <div className="pc-view-14">
                                    {RiskComponents.map((item, index) => (
                                        <div key={index} className="RealEstate-Box">
                                            <h6>{index + 1}.&nbsp;{item.topTitle}</h6>
                                            <hr style={{ opacity: "1" }} />
                                            {item.cardDetails.map((card, cardIndex) => (
                                                <ul key={cardIndex}>
                                                    <li><b>{card.cardBoldText}</b>: {card.cardDescription}</li>
                                                </ul>
                                            ))}
                                        </div>
                                    ))}
                                </div>
                                <div className="mobile-view-14">
                                    <Carousel afterChange={onChange} ref={carouselRef} dots={true} autoplay >
                                        {RiskComponents.map((item, index) => (
                                            <div key={index} className="RealEstate-Box">
                                                <h6>{index + 1}.&nbsp;{item.topTitle}</h6>
                                                <hr style={{ opacity: "1" }} />
                                                {item.cardDetails.map((card, cardIndex) => (
                                                    <ul key={cardIndex}>
                                                        <li><b>{card.cardBoldText}</b>: {card.cardDescription}</li>
                                                    </ul>
                                                ))}
                                            </div>
                                        ))}
                                    </Carousel>
                                </div>

                            </div>
                        </Col>
                    </Row>
                </div>
            </section>
        </>
    )
}
export default SingleResource14;