import React, { useRef , useEffect} from "react";
import CommonResourceComponent from "../commonResourceComponent";
import CommonResourceLeftSide from "../CommonResourceLeftSide";
import { Row, Col, Descriptions,Tabs } from "antd"
import ReactangleTopImage from "./Rectangle.svg"
import DescriptionsItem from "antd/es/descriptions/Item";
import {Module1, Module4} from "../AllResourcesData"
function SingleResource13() {
    const { TabPane } = Tabs;
    const conclusionRef = useRef(null);
    const liList = [
        {
            list: "Real Estate Investment Trusts (REITs)",
            id:"RealEstateInvestmentTrusts(REITs)"

        },
        {
            list: "Vaar",
            id:"Vaar"
        },
        {
            list: "Similarities VS Differences",
            id:"SimilaritiesVSDifferences"
        },
        {
            list: "Conclusion",
            id: "Conclusion"
        }
    ]
    const VaarData = [
        {
            cardMainTitle: "Real Estate Investment Trusts (REITs)",
            cardDetails: [
                {
                    mainPoint: "Structure",
                    Descriptions: "Publicly Traded: REITs are typically publicly traded on stock exchanges, making them easily accessible to a broad range of investors."
                },
                {
                    mainPoint: "Investment Approach",
                    Descriptions: "Portfolio Diversification: REITs own and manage a portfolio of income-generating real estate assets. Investors indirectly own a share of this diversified portfolio."
                },
                {
                    mainPoint: "Liquidity",
                    Descriptions: "Market Liquidity: Being publicly traded, REIT shares can be bought and sold on the stock market, providing investors with liquidity and the ability to exit their investments relatively easily."
                },
                {
                    mainPoint: "Management and Control:",
                    Descriptions: "Passive Ownership: Investors in REITs are passive owners and do not have direct control over the management or decisions related to specific properties. The REIT management team handles property acquisition, management, and sales."
                },
                {
                    mainPoint: "Income Distribution:",
                    Descriptions: "Dividend Payments: REITs are required to distribute at least 90% of their taxable income to shareholders in the form of dividends. Investors receive regular dividend payments, often sourced from rental income."
                }
            ]
        },
        {
            cardMainTitle: "Discreit",
            cardDetails: [
                {
                    mainPoint: "Structure",
                    Descriptions: "Fractional Ownership Platform: Discreit operates as an investment platform that facilitates fractional ownership of individual real estate assets. Investors directly own a portion of a specific property."
                },
                {
                    mainPoint: "Investment Approach:",
                    Descriptions: "Direct Ownership: Discreit allows investors to directly own a fractional share of a specific property, providing them with more control over their individual investments."
                },
                {
                    mainPoint: "Liquidity",
                    Descriptions: "Investment Horizon: Discreit typically views real estate as a long-term investment, with an intended holding period of 3-10 years. While investors receive quarterly dividends, liquidity may be more limited compared to publicly traded REITs."
                },
                {
                    mainPoint: "Management and Control",
                    Descriptions: "Informed Decision-Making: Discreit conducts thorough due diligence on each property before offering it for fractional ownership. This information is provided to investors, allowing for informed decision-making. Investors have a level of control over which specific properties they choose to invest in."
                },
                {
                    mainPoint: "Income Distribution",
                    Descriptions: "Rental Income: Investors on Discreit receive a portion of the rental income generated by the specific property they own. This income is distributed in the form of quarterly dividends."
                }
            ]
        }
    ]
    useEffect(() => {
        window.scrollTo(0, 0); // Scroll to the top when the component mounts or updates
      }, []);
    return (

        <>
            <CommonResourceComponent Resources="Resources" Module="Module 4" Chapter="Concept 1" Date="February 17, 2023" ResourceHeading="FRACTIONALIZATION & VAAR " AuthorInfo="Stephanie Gordon, Content Manager, Vaar" topResourceImg={Module4[2].img} />
            <section>
                <div className="container p-0">
                    <Row>
                        <Col lg={6} md={6} className="hide-on-mobile">
                            <CommonResourceLeftSide MainLeftcontainerHeading="In this chapter" liList={liList} boxTitle="Try the product out for free." />
                        </Col>
                        <Col lg={18} md={18} className="full-width-on-mobile">
                            <div className="resources-right-container">
                                <p id="RealEstateInvestmentTrusts(REITs)">Real Estate Investment Trusts (REITs) and Discreit share similarities in that they both provide a way for investors to gain exposure to real estate without having to directly own and manage physical properties. However, there are key differences in their structures, investment approaches, and the level of control investors have over their investments. Let's delve into the concepts of REITs and Discreit, highlighting both their commonalities and distinctions:</p>
                                <div className="padding-slite"></div>
                                
                                {VaarData.map((item, index) => (
                                    <div key={index} className="RealEstate-Box" id="Vaar">
                                        <h6>{item.cardMainTitle}</h6>
                                        <hr style={{ opacity: "1" }} />
                                        {item.cardDetails.map((card, cardIndex) => (
                                            <ul key={cardIndex}>
                                                <li><b>{card.mainPoint}</b> : {card.Descriptions}</li>

                                            </ul>
                                        ))}
                                    </div>
                                ))}
                                <div className="padding-slite"></div>
                                <h4 id="SimilaritiesVSDifferences">Similarities VS Differences</h4>
                                <div className="pros-cons" id="pros-cons">
                                    <h4>Evaluating Real Estate Investments: Pros and Cons</h4>
                                    <Tabs defaultActiveKey="1">
                                        <TabPane tab="Pros" key="1">
                                            <Row>
                                                    
                                            </Row>
                                        </TabPane>
                                        <TabPane tab="Cons" key="2">
                                            <Row>
                                                
                                            </Row>
                                        </TabPane>
                                    </Tabs>

                                   
                                </div>
                                <h4 id="Conclusion">Conclusion</h4>
                                <p>In summary, both REITs and Discreit provide valuable opportunities for investors to access real estate investments with varying degrees of control, liquidity, and investment horizon. The choice between the two would depend on an investor's preferences, risk tolerance, and investment objectives. REITs may be suitable for those seeking a more liquid and diversified approach, while Discreit offers a more hands-on, direct ownership experience in specific real estate assets.</p>
                            </div>
                        </Col>
                    </Row>


                </div>
            </section>
        </>
    )
}
export default SingleResource13;