import React, { useEffect } from "react";
import CommonResourceComponent from "../commonResourceComponent";
import CommonResourceLeftSide from "../CommonResourceLeftSide";
import { Module1, Module4 } from "../AllResourcesData"
import { Row, Col } from "antd"
import DontMissBlog from "../DontMissBlogs/DontMissBlogs";
import SignupSection from "../../SignUp/SignupSection";
function SingleResource15() {
    const liList = [
        {
            list: "Concepts"
        },
        {
            list: "Conclusion"
        }
    ]

    const concept5Data = [
        {
            topTitle: "Fractional Ownership",
            cardDetails: [
                {
                    cardBoldText: "Traditional Barrier",
                    cardDescription: "Residential real estate often requires a significant upfront investment, making it inaccessible to many individuals."
                },
                {
                    cardBoldText: "Discreit's Solution",
                    cardDescription: "Discreit introduces fractional ownership, allowing investors to buy and own a fraction of a residential property. This eliminates the need for a large upfront capital investment, making real estate accessible to a broader range of investors with varying financial capacities."
                }
            ]
        },
        {
            topTitle: "Lowering Entry Barriers",
            cardDetails: [
                {
                    cardBoldText: "Traditional Barrier",
                    cardDescription: "High minimum investment amounts can exclude smaller investors from participating in the real estate market."
                },
                {
                    cardBoldText: "Discreit's Solution",
                    cardDescription: "By lowering the entry barriers, Discreit allows individuals to start investing in residential real estate with a fraction of the typical cost. This inclusivity opens up wealth-building opportunities for a more diverse investor base."
                }
            ]
        },
        {
            topTitle: "Diversification Opportunities",
            cardDetails: [
                {
                    cardBoldText: "Traditional Barrier",
                    cardDescription: "Diversifying across multiple properties is challenging for individual investors due to capital constraints."
                },
                {
                    cardBoldText: "Discreit's Solution",
                    cardDescription: "Through fractional ownership, Discreit enables investors to diversify their real estate portfolio by owning fractions of multiple residential properties. This diversification helps mitigate risk and provides exposure to different housing markets."
                }
            ]
        },
        {
            topTitle: "User-Friendly Interface",
            cardDetails: [
                {
                    cardBoldText: "Traditional Barrier",
                    cardDescription: "Complexity and lack of transparency in real estate transactions can deter potential investors."
                },
                {
                    cardBoldText: "Discreit's Solution",
                    cardDescription: "Discreit offers an intuitive and user-friendly platform that simplifies the real estate investment process. The platform's interface guides users through research, investment decisions, and ongoing management, making it accessible to individuals regardless of their experience in real estate."
                }
            ]
        },
        {
            topTitle: "Thorough Due Diligence",
            cardDetails: [
                {
                    cardBoldText: "Traditional Barrier",
                    cardDescription: "Lack of information and transparency in real estate transactions can lead to investment hesitations."
                },
                {
                    cardBoldText: "Discreit's Solution",
                    cardDescription: "Discreit conducts thorough due diligence on each residential property before offering it for fractional ownership. This comprehensive research ensures that investors have access to clean and transparent information, empowering them to make well-informed investment decisions."
                }
            ]
        },
        {
            topTitle: "Regular Income Distribution",
            cardDetails: [
                {
                    cardBoldText: "Traditional Barrier",
                    cardDescription: "Real estate income is often generated through property ownership, which can be a challenge for smaller investors."
                },
                {
                    cardBoldText: "Discreit's Solution",
                    cardDescription: "Investors on Discreit receive a share of the rental income generated by the residential properties they own. This income is distributed in the form of quarterly dividends, providing a regular and predictable stream of passive income."
                }
            ]
        },
        {
            topTitle: "Long-Term Investment Perspective",
            cardDetails: [
                {
                    cardBoldText: "Traditional Barrier",
                    cardDescription: "Real estate transactions are often perceived as long-term commitments, potentially deterring some investors."
                },
                {
                    cardBoldText: "Discreit's Solution",
                    cardDescription: "Discreit embraces a long-term investment horizon, aligning with the nature of residential real estate. This perspective encourages investors to view real estate as a stable and enduring asset class."
                }
            ]
        },
        {
            topTitle: "Transparency and Information Access",
            cardDetails: [
                {
                    cardBoldText: "Traditional Barrier",
                    cardDescription: " Information asymmetry and lack of transparency in real estate transactions can hinder decision-making."
                },
                {
                    cardBoldText: "Discreit's Solution",
                    cardDescription: "Transparency is a priority for Discreit. The platform discloses and breaks down all costs and figures related to each residential property, ensuring investors have access to the necessary information to make informed decisions."
                }
            ]
        }
    ]
    useEffect(() => {
        window.scrollTo(0, 0); // Scroll to the top when the component mounts or updates
    }, []);
    return (
        <>
            <CommonResourceComponent Resources="Resources" Module="Module 4" Chapter="Concept 5" Date="February 17, 2023" ResourceHeading="Access the Largest Asset Class in the US" AuthorInfo="Stephanie Gordon, Content Manager, Vaar" topResourceImg={Module4[4].img} />
            <section>
                <div className="container p-0">
                    <Row>
                        <Col lg={6} md={6} className="hide-on-mobile">
                            <CommonResourceLeftSide MainLeftcontainerHeading="In this chapter" liList={liList} boxTitle="Try the product out for free." />
                        </Col>
                        <Col lg={18} md={18} className="full-width-on-mobile">
                            <div className="resources-right-container">
                                <p>Discreit revolutionizes the accessibility of the largest asset class in the US, residential real estate, by addressing traditional barriers and democratizing investment opportunities. Here's how Discreit makes residential real estate accessible to everyone:</p>
                                <div className="padding-slite"></div>
                                <div>
                                    {/* <Carousel afterChange={onChange} ref={carouselRef} dots={true}  > */}
                                    {concept5Data.map((item, index) => (
                                        <div key={index} className="RealEstate-Box">
                                            <h6>{item.topTitle}</h6>
                                            <hr style={{ opacity: "1" }} />
                                            {item.cardDetails.map((card, cardIndex) => (
                                                <ul key={cardIndex}>
                                                    <li><b>{card.cardBoldText}</b>: {card.cardDescription}</li>
                                                </ul>
                                            ))}
                                        </div>
                                    ))}
                                    {/* </Carousel> */}
                                </div>
                                <div className="padding-slite"></div>
                                <h4>Conclusion</h4>
                                <p>In summary, Discreit's innovative approach to fractional ownership removes long standing barriers, making residential real estate, the largest asset class in the US, accessible to a wider audience. Through lower entry barriers, diversification opportunities, user-friendly interfaces, thorough due diligence, and transparent processes, Discreit empowers individuals of various financial backgrounds to participate in the wealth-building potential of residential real estate.</p>
                            </div>
                        </Col>
                    </Row>
                    <div className="padding-slite"></div>
                    <div className="padding-slite"></div>
                    <DontMissBlog/>
                </div>
            </section>
            <SignupSection/>
        </>
    )
}
export default SingleResource15;