import React, { useRef, useEffect, useState } from "react";
import CommonResourceComponent from "../commonResourceComponent";
import CommonResourceLeftSide from "../CommonResourceLeftSide";
import { Row, Col, Descriptions, Tabs } from "antd"
import ReactangleTopImage from "./Rectangle.svg"
import DescriptionsItem from "antd/es/descriptions/Item";
import { Module1, Module4 } from "../AllResourcesData"
import linkIndex from "../utils/linkIndex";
import DontMissBlog from "../DontMissBlogs/DontMissBlogs";
import SignupSection from "../../SignUp/SignupSection";
import { Swiper, SwiperSlide } from 'swiper/react';
// Import Swiper styles
import 'swiper/css';
import 'swiper/css/pagination';
import { Pagination } from 'swiper/modules';
function SingleResource13() {

    const [activeTab, setActiveTab] = useState('pros');
    const { TabPane } = Tabs;
    const conclusionRef = useRef(null);
    const liList = [
        {
            list: "Real Estate Investment Trusts (REITs)",
            id: "RealEstateInvestmentTrusts(REITs)"

        },
        {
            list: "Vaar",
            id: "Vaar"
        },
        {
            list: "Similarities VS Differences",
            id: "SimilaritiesVSDifferences"
        },
        {
            list: "Conclusion",
            id: "Conclusion"
        }
    ]
    const VaarData = [
        {
            cardMainTitle: "Real Estate Investment Trusts (REITs)",
            cardDetails: [
                {
                    mainPoint: "Structure",
                    Descriptions: "Publicly Traded: REITs are typically publicly traded on stock exchanges, making them easily accessible to a broad range of investors."
                },
                {
                    mainPoint: "Investment Approach",
                    Descriptions: "Portfolio Diversification: REITs own and manage a portfolio of income-generating real estate assets. Investors indirectly own a share of this diversified portfolio."
                },
                {
                    mainPoint: "Liquidity",
                    Descriptions: "Market Liquidity: Being publicly traded, REIT shares can be bought and sold on the stock market, providing investors with liquidity and the ability to exit their investments relatively easily."
                },
                {
                    mainPoint: "Management and Control:",
                    Descriptions: "Passive Ownership: Investors in REITs are passive owners and do not have direct control over the management or decisions related to specific properties. The REIT management team handles property acquisition, management, and sales."
                },
                {
                    mainPoint: "Income Distribution:",
                    Descriptions: "Dividend Payments: REITs are required to distribute at least 90% of their taxable income to shareholders in the form of dividends. Investors receive regular dividend payments, often sourced from rental income."
                }
            ]
        },
        {
            cardMainTitle: "Vaar",
            cardDetails: [
                {
                    mainPoint: "Structure",
                    Descriptions: "Fractional Ownership Platform: Vaar operates as an investment platform that facilitates fractional ownership of individual real estate assets. Investors directly own a portion of a specific property."
                },
                {
                    mainPoint: "Investment Approach:",
                    Descriptions: "Direct Ownership: Vaar allows investors to directly own a fractional share of a specific property, providing them with more control over their individual investments."
                },
                {
                    mainPoint: "Liquidity",
                    Descriptions: "Investment Horizon: Vaar typically views real estate as a long-term investment, with an intended holding period of 3-10 years. While investors receive quarterly dividends, liquidity may be more limited compared to publicly traded REITs."
                },
                {
                    mainPoint: "Management and Control",
                    Descriptions: "Informed Decision-Making: Vaar conducts thorough due diligence on each property before offering it for fractional ownership. This information is provided to investors, allowing for informed decision-making. Investors have a level of control over which specific properties they choose to invest in."
                },
                {
                    mainPoint: "Income Distribution",
                    Descriptions: "Rental Income: Investors on Vaar receive a portion of the rental income generated by the specific property they own. This income is distributed in the form of quarterly dividends."
                }
            ]
        }
    ]
    const Similarities = [
        {
            title: "Access to Real Estate:",
            Descriptions: "Both REITs and Discreit provide investors with a means to access real estate investments without the need for direct property ownership."
        },
        {
            title: "Income Generation:",
            Descriptions: "Both investment vehicles offer a source of income to investors through rental income (in the case of Discreit) or dividend payments (in the case of REITs)."
        },
        {
            title: "Diversification:",
            Descriptions: "Both REITs and Discreit allow for diversification within the real estate asset class, mitigating risks associated with individual properties."
        },
        {
            title: "Passive Income:",
            Descriptions: "Investors in both REITs and Discreit can benefit from passive income generated by the underlying real estate assets."
        }
    ]

    const Differences = [
        {
            title: "Ownership Structure:",
            Descriptions: "REITs involve indirect ownership through shares of a publicly traded company, while Discreit enables direct fractional ownership of individual properties."
        },
        {
            title: "Control and Decision-Making:",
            Descriptions: "Discreit offers investors more control and involvement in the decision-making process regarding which specific properties to invest in, while REIT investors have limited control over individual property decisions."
        },
        {
            title: "Liquidity:",
            Descriptions: "REITs, being publicly traded, offer higher liquidity with shares traded on stock exchanges. Discreit, with a focus on long-term investment, may have more limited liquidity."
        },
        {
            title: "Investment Horizon:",
            Descriptions: "Discreit generally adopts a longer investment horizon, holding properties for 3-10 years, while REITs can provide more flexibility for investors to buy and sell shares on the stock market."
        }
    ]
    const handleTabChange = (tab) => {
        setActiveTab(tab);
    };

    useEffect(() => {
        window.scrollTo(0, 0); // Scroll to the top when the component mounts or updates
    }, []);
    return (

        <>
            <CommonResourceComponent Resources="Resources" Module="Module 4" Chapter="Concept 3" Date="February 17, 2023" ResourceHeading="REITs & Vaar" AuthorInfo="Stephanie Gordon, Content Manager, Vaar" topResourceImg={Module4[2].img} />
            <section>
                <div className="container p-0">
                    <Row>
                        <Col lg={6} md={6} className="hide-on-mobile">
                            <CommonResourceLeftSide MainLeftcontainerHeading="In this chapter" liList={liList} boxTitle="Try the product out for free." />
                        </Col>
                        <Col lg={18} md={18} className="full-width-on-mobile">
                            <div className="resources-right-container">
                                <p id="RealEstateInvestmentTrusts(REITs)">Real Estate Investment Trusts (REITs) and Vaar share similarities in that they both provide a way for investors to gain exposure to real estate without having to directly own and manage physical properties. However, there are key differences in their structures, investment approaches, and the level of control investors have over their investments. Let's delve into the concepts of REITs and Vaar, highlighting both their commonalities and distinctions:</p>
                                <div className="padding-slite"></div>

                                {VaarData.map((item, index) => (
                                    <div key={index} className="RealEstate-Box" id="Vaar">
                                        <h6>{item.cardMainTitle}</h6>
                                        <hr style={{ opacity: "1" }} />
                                        {item.cardDetails.map((card, cardIndex) => (
                                            <ul key={cardIndex}>
                                                <li><b>{card.mainPoint}</b> : {card.Descriptions}</li>

                                            </ul>
                                        ))}
                                    </div>
                                ))}
                                <div className="padding-slite"></div>
                                <h4 id="SimilaritiesVSDifferences">Similarities VS Differences</h4>
                                <div className="pros-cons" id="pros-cons">
                                    <h4>Evaluating Real Estate Investments: Pros and Cons</h4>
                                    <div>
                                        <div style={{ marginBottom: '10px' }}>
                                            <button
                                                style={{ backgroundColor: activeTab === 'pros' ? '#D4F604' : 'rgb(0, 0, 0)', color: activeTab === 'pros' ? 'black' : 'white' }}
                                                onClick={() => handleTabChange('pros')}
                                            >
                                                Pros
                                            </button>
                                            <button
                                                style={{ backgroundColor: activeTab === 'cons' ? '#D4F604' : 'rgb(0, 0, 0)', color: activeTab === 'pros' ? 'white' : 'black' }}
                                                onClick={() => handleTabChange('cons')}
                                            >
                                                Cons
                                            </button>
                                        </div>

                                        
                                        <div className="visible-for-pc">
                                        <Row>
                                            {activeTab === 'pros' &&
                                                Similarities.map((item, index) => (
                                                    <Col lg={12} md={24} key={index} style={{ margin: '10px 0px' }}>
                                                        <div className="EvalutionCardbox">
                                                            <h6>{item.title}</h6>
                                                            <hr />
                                                            <p>{item.Descriptions}</p>
                                                        </div>
                                                    </Col>
                                                ))}
                                            {activeTab === 'cons' &&
                                                Differences.map((item, index) => (
                                                    <Col lg={12} md={24} key={index} style={{ margin: '10px 0px' }}>
                                                        <div className="EvalutionCardbox">
                                                            <h6>{item.title}</h6>
                                                            <hr />
                                                            <p>{item.Descriptions}</p>
                                                        </div>
                                                    </Col>
                                                ))}
                                        </Row>
                                        </div>
                                        <div className="visible-for-mobile">
                                            <Row>
                                                <Swiper pagination={{ clickable: true }} modules={[Pagination]} className="mySwiper">
                                                    {activeTab === 'pros' &&
                                                        Similarities.map((item, index) => (
                                                            <SwiperSlide key={index}>
                                                                <Col lg={24} md={24} style={{ margin: '10px 0px' }}>
                                                                    <div className="EvalutionCardbox">
                                                                        <h6>{item.title}</h6>
                                                                        <hr />
                                                                        <p>{item.Descriptions}</p>
                                                                    </div>
                                                                </Col>
                                                            </SwiperSlide>
                                                        ))
                                                    }
                                                </Swiper>
                                                <Swiper pagination={{ clickable: true }} modules={[Pagination]} className="mySwiper">
                                                    {activeTab === 'cons' &&
                                                        Differences.map((item, index) => (
                                                            <SwiperSlide key={index}>
                                                                <Col lg={24} md={24} style={{ margin: '10px 0px' }}>
                                                                    <div className="EvalutionCardbox">
                                                                        <h6>{item.title}</h6>
                                                                        <hr />
                                                                        <p>{item.Descriptions}</p>
                                                                    </div>
                                                                </Col>
                                                            </SwiperSlide>
                                                        ))
                                                    }
                                                </Swiper>
                                            </Row>
                                        </div>

                                    </div>

                                </div>
                                <h4 id="Conclusion">Conclusion</h4>
                                <p>In summary, both REITs and Vaar provide valuable opportunities for investors to access real estate investments with varying degrees of control, liquidity, and investment horizon. The choice between the two would depend on an investor's preferences, risk tolerance, and investment objectives. REITs may be suitable for those seeking a more liquid and diversified approach, while Vaar offers a more hands-on, direct ownership experience in specific real estate assets.</p>
                            </div>
                        </Col>
                    </Row>
                    <div className="padding-slite"></div>
                    <div className="padding-slite"></div>
                    <DontMissBlog index={[10, 12]} />

                </div>
            </section>
            <SignupSection />
        </>
    )
}
export default SingleResource13;